{% set name = "UpSetPlot" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95b76ac38c624c9dfb1eca1de1a37e30e07e83678b1c57839c943184247b8592

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pandas
    - matplotlib-base >=2.0
    - pytest-runner
  run:
    - python >=3.6
    - pandas
    - matplotlib-base >=2.0

test:
  imports:
    - upsetplot

about:
  home: https://github.com/jnothman/UpSetPlot
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Creating upsetplots in Python

extra:
  recipe-maintainers:
    - wdecoster
